### ISSUE TITLE
Bindless tests require > 1GB VRAM

### ISSUE THREAD

**Issue by michaelmarks** [nvMcJohn/apitest#10]
The GLBindless & GLBindlessIndirect solutions to the UntexturedObjects fail to render  on my Ubuntu 14.04 LTS system running the 331.79 drivers on an Nvidia 750. Watching available VRAM, these solutions appear to blow video memory. VRAM raises rapidly, appears to crash down to initial VRAM usage, then increase again.

Rendering 32x32x32 cubes works fine.

Whether the Nvidia driver should use that much VRAM is a question I didn't research.

**Comment by daVinci1980** [comment]
These tests consume virtual address space, but not physical address space. This means they don't need actual ram backing the textures.

**Comment by michaelmarks** [comment]
My comment, almost a year ago, was really a bug report that contained a potentially false diagnosis. With the above config, nothing renders onscreen (bug). As an aside, I noticed the reported free vram went to 0 during the test.

My experiences with apitest on Linux last year uncovered multiple driver bugs on AMD, this may have just been another bug.
