### ISSUE TITLE
SDL compile issue on ubuntu 14

### ISSUE THREAD

**Issue by joessu** [nvMcJohn/apitest#17]
../thirdparty/SDL2-2.0.1//libSDL2.a(SDL_sysjoystick.c.o): In function `JoystickInitWithUdev':
/home/joessu/Clionprojects/apitest/thirdparty/SDL2-2.0.1/src/joystick/linux/SDL_sysjoystick.c:330: undefined reference to `SDL_UDEV_Init'
/home/joessu/Clionprojects/apitest/thirdparty/SDL2-2.0.1/src/joystick/linux/SDL_sysjoystick.c:335: undefined reference to `SDL_UDEV_AddCallback'
/home/joessu/Clionprojects/apitest/thirdparty/SDL2-2.0.1/src/joystick/linux/SDL_sysjoystick.c:341: undefined reference to `SDL_UDEV_Scan'
/home/joessu/Clionprojects/apitest/thirdparty/SDL2-2.0.1/src/joystick/linux/SDL_sysjoystick.c:336: undefined reference to `SDL_UDEV_Quit'
../thirdparty/SDL2-2.0.1//libSDL2.a(SDL_sysjoystick.c.o): In function `SDL_SYS_JoystickQuit':
/home/joessu/Clionprojects/apitest/thirdparty/SDL2-2.0.1/src/joystick/linux/SDL_sysjoystick.c:859: undefined reference to `SDL_UDEV_DelCallback'
../thirdparty/SDL2-2.0.1//libSDL2.a(SDL_sysjoystick.c.o): In function `SDL_SYS_JoystickDetect':
/home/joessu/Clionprojects/apitest/thirdparty/SDL2-2.0.1/src/joystick/linux/SDL_sysjoystick.c:381: undefined reference to `SDL_UDEV_Poll'
../thirdparty/SDL2-2.0.1//libSDL2.a(SDL_sysjoystick.c.o): In function `SDL_SYS_JoystickQuit':
/home/joessu/Clionprojects/apitest/thirdparty/SDL2-2.0.1/src/joystick/linux/SDL_sysjoystick.c:860: undefined reference to `SDL_UDEV_Quit'
collect2: error: ld returned 1 exit status
make[3]: *** [/home/joessu/Clionprojects/apitest/bin/apitest_d] Error 1
make[2]: *** [src/CMakeFiles/apitest.dir/all] Error 2
make[1]: *** [src/CMakeFiles/apitest.dir/rule] Error 2
make: *** [apitest] Error 2

tried to install different debians but still the same result. Any ideas how to fix?

**Comment by joessu** [comment]
i tried https://github.com/PluginIO/EX3/wiki/Setting-up-SDL2-in-Ubuntu-12.10 but still get the same issues.

**Comment by joessu** [comment]
Actually, i removed old SDL and then (using clion) targeted the different SDL targets individually, then it built. I did comment out some of the SDL joystick stuff.

**Comment by elect86** [comment]
Hi,

I have exactly the same issues

Can you explain all the steps you took?

**Comment by elect86** [comment]
Solved by commenting out all those lines..
