### ISSUE TITLE
OS X: Seeing lots of shader compilation/linking failed

### ISSUE THREAD

**Issue by buzmeg** [nvMcJohn/apitest#19]
I see a lot of messages like this on OS X:
Warning: Unable to initialize solution 'GLMultiDrawBuffer-NoSDP', shader compilation/linking failed.

SDL and cmake are from the latest homebrew.  OS X 10.9.5 on a Macbook Pro Retina.

I also see a bunch of SDL messages like this:
opengl/apitest/thirdparty/SDL2-2.0.1/src/haptic/darwin/SDL_syshaptic.c:130:10: warning: overflow converting case value to switch condition type (2147746313 to -2147220983) [-Wswitch]
    case FFERR_UNPLUGGED:

Thanks.

**Comment by vMcJohn** [comment]
OSX doesn't support a lot of the extensions that we are capable of using on Linux and Windows, sadly. Those solutions should fail to initialize, but the app should still work. Is that what you're seeing?

**Comment by buzmeg** [comment]
The issue is that solutions that do appear to have the required extensions aren't running.

The missing extensions appear to give a different warning:
Solution GLTextureArrayMultiDraw-SDP - Initializing.
Warning: Unable to initialize solution, ARB_shader_draw_parameters is required but not available.
Solution GLTextureArrayMultiDraw-SDP - Initialize complete (Success: false).
Solution GLTextureArrayMultiDraw-SDP - shutdown beginning.
Solution GLTextureArrayMultiDraw-SDP shutdown complete.


While the shader/linking is:
Solution GLTextureArray - Initializing.
Warning: Unable to initialize solution 'GLTextureArray', shader compilation/linking failed.
Solution GLTextureArray - Initialize complete (Success: false).
Solution GLTextureArray - shutdown beginning.
Solution GLTextureArray shutdown complete.

**Comment by vMcJohn** [comment]
For the first solution:
Warning: Unable to initialize solution, ARB_shader_draw_parameters is required but not available.

For the second:
Warning: Unable to initialize solution 'GLTextureArray', shader compilation/linking failed.

This is telling you that these don't work on the platform and why.

**Comment by buzmeg** [comment]
Oh, there is something in the shader that is unsupported?

I was assuming that a shader compilation/linking failure was a failure of toolchain, not a failure of OpenGL feature.

My mistake.  Sorry.

**Comment by vMcJohn** [comment]
I'll look into the compilation failure on my OSX system, it's possible there's a bug in the shader--and even if not I can report the compilation issue to clarify why the failure occurred which would make it more obvious that this is a platform limitation, not a toolchain issue.

Thanks for the report!

**Comment by buzmeg** [comment]
Project dead.  Closing.
