### ISSUE TITLE
Question about synchronization

### ISSUE THREAD

**Issue by MarkSakharov** [nvMcJohn/apitest#26]
Hello!

In apitest main loop looks like this:
while(1)
{
    render();
    SwapBuffers();
}

Why would we ever need a synchronization (triple buffer + fence) while SwapBuffers is equivalent to glFinish thus on next render() call GPU will be free of work?

**Comment by MarkSakharov** [comment]
https://www.khronos.org/opengl/wiki/Swap_Interval

**Comment by daVinci1980** [comment]
I see that you answered your own question, but I figured I'd clarify here for anyone else that finds this issue--SwapBuffers is not equivalent to glFinish. SwapBuffers queues up a command to swap the back buffer to the front buffer. It does insert a GPU fence to ensure that all other writes to the render target are complete before rendering, but that fence is not waited for on the CPU--only the GPU.

Hope this helps.

**Comment by MarkSakharov** [comment]
"SwapBuffers queues up a command" - that's it.
Thanks for reply!
